# Some settings taken from here
# https://docs.astral.sh/ruff/configuration/


[tool.ruff]
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".ruff_cache",
    ".vscode",
    "__pypackages__",
    "_build",
    "site-packages",
    "venv",
    "README.md"
]

# Same as Black
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = [
    "E", # pycodestyle error
    "W", # pycodestyle warning
    "C90", # mccabe complexity
    "N", # pep8-naming,
    "F", # Pyflakes
    "I", # isort
    "B", # flake8-bugbear
    "PL", # pylint,
    "PD", # pandas-vet
    "RUF", # Ruff-specific rules
    "NPY", # NumPy-specific rules
    "Q", # flake8-quotes (TBD, may be too aggressive)
]
ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
"__init__.py" = ["E402"]

# this might be nice if I want to have own module
# [tool.ruff.isort]
# known-first-party = ["myproject"]

# TO DO:
# add coverage
# mypy?
# see what else to add from ruff documentation